# Site settings
email: "soso2501@gmail.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Fade Temple
description: 枯燥乏味，愤世嫉俗，灵光乍现，铭之
url: ""
twitter_username: 
default_img: 

# Profile settings
name: 小差小差
profile_img: 
profile: 
social:
  github: https://github.com/xiaochai
  weibo: http://weibo.com/lqso

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
